apiVersion: v1
kind: List
metadata:
  name: flask-dummy
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: flask-dummy
    name: flask-dummy
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      deploymentconfig: flask-dummy
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: flask-dummy
  spec:
    replicas: 1
    selector:
      deploymentconfig: flask-dummy
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: flask-dummy
      spec:
        containers:
        - image: REGIP:5000/myproject/flask-demo
          name: flask-dummy
          ports:
          - containerPort: 5000
            protocol: TCP
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: flask-dummy
  spec:
    dockerImageRepository:  
- apiVersion: v1
  kind: Route
  metadata:
    name: flask-dummy
  spec:
    to:
      kind: Service
      name: flask-dummy
